//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace do_an_cnpm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BACSI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BACSI()
        {
            this.CAKHAMs = new HashSet<CAKHAM>();
            this.DONTHUOCs = new HashSet<DONTHUOC>();
            this.PHIEUCHUPCTs = new HashSet<PHIEUCHUPCT>();
            this.PHIEUCHUPXQUANGs = new HashSet<PHIEUCHUPXQUANG>();
            this.PHIEUHENTAIKHAMs = new HashSet<PHIEUHENTAIKHAM>();
            this.PHIEUXETNGHIEMs = new HashSet<PHIEUXETNGHIEM>();
        }
    
        public int MaBacSi { get; set; }
        public string TenBacSi { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> SDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAKHAM> CAKHAMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONTHUOC> DONTHUOCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUCHUPCT> PHIEUCHUPCTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUCHUPXQUANG> PHIEUCHUPXQUANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUHENTAIKHAM> PHIEUHENTAIKHAMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUXETNGHIEM> PHIEUXETNGHIEMs { get; set; }

        public List<BACSI> BSCollection { get; set; }
    }
}
