//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace do_an_cnpm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENHNHAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BENHNHAN()
        {
            this.CAKHAMs = new HashSet<CAKHAM>();
            this.DONTHUOCs = new HashSet<DONTHUOC>();
            this.HOADONs = new HashSet<HOADON>();
            this.PHIEUCHUPCTs = new HashSet<PHIEUCHUPCT>();
            this.PHIEUCHUPXQUANGs = new HashSet<PHIEUCHUPXQUANG>();
            this.PHIEUDANGKYKHAMBENHs = new HashSet<PHIEUDANGKYKHAMBENH>();
            this.PHIEUHENTAIKHAMs = new HashSet<PHIEUHENTAIKHAM>();
            this.PHIEUXETNGHIEMs = new HashSet<PHIEUXETNGHIEM>();
        }
    
        public int MaBN { get; set; }
        public string HoTen { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> NgayKham { get; set; }
        public string LoaiBenh { get; set; }
        public string TrieuChung { get; set; }
        public string LoaiDichVu { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        public Nullable<int> MaKG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAKHAM> CAKHAMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONTHUOC> DONTHUOCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUCHUPCT> PHIEUCHUPCTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUCHUPXQUANG> PHIEUCHUPXQUANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUDANGKYKHAMBENH> PHIEUDANGKYKHAMBENHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUHENTAIKHAM> PHIEUHENTAIKHAMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUXETNGHIEM> PHIEUXETNGHIEMs { get; set; }
        public virtual KHUNGGIO KHUNGGIO { get; set; }

        public List<BENHNHAN> BNCollection { get; set; }
    }
}
