//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace do_an_cnpm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUNHAPTHUOC
    {
        public int MaCTPNT { get; set; }
        public Nullable<int> MaPNT { get; set; }
        public Nullable<int> MaThuoc { get; set; }
        public Nullable<int> DonGiaNhap { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> ThanTien { get; set; }
    
        public virtual PHIEUNHAPTHUOC PHIEUNHAPTHUOC { get; set; }
        public virtual THUOC THUOC { get; set; }
    }
}
