//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace do_an_cnpm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOANHTHUTIENTHUOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOANHTHUTIENTHUOC()
        {
            this.CTDTTIENTHUOCs = new HashSet<CTDTTIENTHUOC>();
        }
    
        public int MaDTTT { get; set; }
        public Nullable<System.DateTime> Thang { get; set; }
        public Nullable<int> DoanhThu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDTTIENTHUOC> CTDTTIENTHUOCs { get; set; }
    }
}
