//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace do_an_cnpm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBPhongmachEntities : DbContext
    {
        public DBPhongmachEntities()
            : base("name=DBPhongmachEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMINISTRATOR> ADMINISTRATORs { get; set; }
        public virtual DbSet<BACSI> BACSIs { get; set; }
        public virtual DbSet<BENHNHAN> BENHNHANs { get; set; }
        public virtual DbSet<CAKHAM> CAKHAMs { get; set; }
        public virtual DbSet<CHITIETDONTHUOC> CHITIETDONTHUOCs { get; set; }
        public virtual DbSet<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual DbSet<CHITIETPHIEUNHAPTHUOC> CHITIETPHIEUNHAPTHUOCs { get; set; }
        public virtual DbSet<CHUCVU> CHUCVUs { get; set; }
        public virtual DbSet<CTDTTIENKHAM> CTDTTIENKHAMs { get; set; }
        public virtual DbSet<CTDTTIENTHUOC> CTDTTIENTHUOCs { get; set; }
        public virtual DbSet<DOANHTHUTIENKHAM> DOANHTHUTIENKHAMs { get; set; }
        public virtual DbSet<DOANHTHUTIENTHUOC> DOANHTHUTIENTHUOCs { get; set; }
        public virtual DbSet<DONTHUOC> DONTHUOCs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<LETAN> LETANs { get; set; }
        public virtual DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public virtual DbSet<PHIEUCHUPCT> PHIEUCHUPCTs { get; set; }
        public virtual DbSet<PHIEUCHUPXQUANG> PHIEUCHUPXQUANGs { get; set; }
        public virtual DbSet<PHIEUDANGKYKHAMBENH> PHIEUDANGKYKHAMBENHs { get; set; }
        public virtual DbSet<PHIEUHENTAIKHAM> PHIEUHENTAIKHAMs { get; set; }
        public virtual DbSet<PHIEUNHAPTHUOC> PHIEUNHAPTHUOCs { get; set; }
        public virtual DbSet<PHIEUXETNGHIEM> PHIEUXETNGHIEMs { get; set; }
        public virtual DbSet<THUOC> THUOCs { get; set; }
        public virtual DbSet<THUKHO> THUKHOes { get; set; }
        public virtual DbSet<KHUNGGIO> KHUNGGIOs { get; set; }
    }
}
